  
MODEL:
  model_name: TRIPLEX 
  num_genes: 250
  emb_dim: 512
  depth1: 2
  depth2: 2
  depth3: 4
  num_heads1: 8
  num_heads2: 16
  num_heads3: 16
  mlp_ratio1: 4
  mlp_ratio2: 1
  mlp_ratio3: 1
  dropout1: 0.1
  dropout2: 0.1
  dropout3: 0.3
  kernel_size: 3
  pos_layer: 'APEG' # 'MLP' or 'None'

DATA:
  dataset_name: TriDataset