

GENERAL:
  seed: 2021
  log_path: ./logs
  
TRAINING:
  num_k: 5
  learning_rate: 1.0e-4
  num_epochs: 200
  monitor: PearsonCorrCoef
  mode: max
  early_stopping:
    patience: 20
  lr_scheduler:
    patience: 5
    factor: 0.1
  
DATA:
  data_dir: /home/shared/chungym/hier_st/input/takano/xenium
  output_dir: output/pred/takano/xenium
  gene_type: 'var'
  gene_type: 'all'
  num_genes: 302
  num_outputs: 302
  
  train_dataloader:
        batch_size: 128
        num_workers: 4
        pin_memory: False
        shuffle: True

  test_dataloader:
      batch_size: 1
      num_workers: 4
      pin_memory: False
      shuffle: False