GENERAL:
  seed: 2021
  log_path: ./logs
  
TRAINING:
  num_k: 5
  learning_rate: 1.0e-4
  num_epochs: 200
  monitor: PearsonCorrCoef
  mode: min
  early_stopping:
    patience: 10
  lr_scheduler:
    patience: 5
    factor: 0.1
  
MODEL:
  model_name: BLEEP
  temperature: 1.0
  image_embedding: 512
  spot_embedding: 302
  projection_dim: 512
  trainable: True
  dropout: 0.1

DATA:
  data_dir: input/takano/xenium
  output_dir: output/pred/takano/xenium
  dataset_name: BleepDataset
  gene_type: 'all'
  num_genes: 302
  num_outputs: 302
  cpm: False
  smooth: False
  
  train_dataloader:
        batch_size: 64
        num_workers: 4
        pin_memory: True
        shuffle: True

  test_dataloader:
      batch_size: 1
      num_workers: 4
      pin_memory: True
      shuffle: False