GENERAL:
  seed: 2021
  log_path: ./logs
  
TRAINING:
  num_k: 5
  learning_rate: 1.0e-4
  num_epochs: 200
  monitor: PearsonCorrCoef
  mode: max
  early_stopping:
    patience: 10
  lr_scheduler:
    patience: 5
    factor: 0.1
  
MODEL:
  model_name: TRIPLEX 
  num_outputs: 302
  emb_dim: 1024
  depth1: 1
  depth2: 2
  depth3: 2
  num_heads1: 8
  num_heads2: 16
  num_heads3: 16
  mlp_ratio1: 2
  mlp_ratio2: 2
  mlp_ratio3: 2
  dropout1: 0.15
  dropout1: 0.15
  dropout1: 0.15
  kernel_size: 3

DATA:
  data_dir: input/takano/xenium
  output_dir: output/pred/takano/xenium
  dataset_name: TriDataset
  gene_type: 'all'
  num_genes: 302
  num_outputs: 302
  cpm: False
  smooth: False
  
  train_dataloader:
        batch_size: 128
        num_workers: 4
        pin_memory: True
        shuffle: True

  test_dataloader:
      batch_size: 1
      num_workers: 4
      pin_memory: True
      shuffle: False