

GENERAL:
  seed: 2021
  log_path: ./logs
  
TRAINING:
  num_k: 2
  learning_rate: 1.0e-4
  num_epochs: 200
  monitor: PearsonCorrCoef
  mode: max
  early_stopping:
    patience: 10
  lr_scheduler:
    patience: 5
    factor: 0.1
  
MODEL:
  model_name: st_net 
  num_outputs: 50

DATA:
  data_dir: input/hest/bench_data/READ
  output_dir: output/pred/hest/bench_data/READ
  dataset_name: STDataset
  gene_type: 'var'
  num_genes: 50
  num_outputs: 50
  
  train_dataloader:
        batch_size: 128
        num_workers: 4
        pin_memory: False
        shuffle: True

  test_dataloader:
      batch_size: 1
      num_workers: 4
      pin_memory: False
      shuffle: False