
TRAINING:
  mode: min
    
MODEL:
  model_name: BLEEP
  temperature: 1.0
  image_embedding: 512
  spot_embedding: 300
  projection_dim: 512
  trainable: True
  dropout: 0.1

DATA:
  dataset_name: BleepDataset
  