
MODEL:
  model_name: TRIPLEX 
  emb_dim: 1024
  depth1: 1
  depth2: 2
  depth3: 2
  num_heads1: 8
  num_heads2: 16
  num_heads3: 16
  mlp_ratio1: 2
  mlp_ratio2: 2
  mlp_ratio3: 2
  dropout1: 0.15
  dropout1: 0.15
  dropout1: 0.15
  kernel_size: 3
  pos_layer: 'APEG' # 'MLP' or 'None' or "spatialformer"

DATA:
  dataset_name: TriDataset