
MODEL:
  model_name: TRIPLEX 
  num_outputs: 300
  emb_dim: 1024
  depth1: 1
  depth2: 2
  depth3: 2
  num_heads1: 8
  num_heads2: 16
  num_heads3: 16
  mlp_ratio1: 2
  mlp_ratio2: 2
  mlp_ratio3: 2
  dropout1: 0.15
  dropout1: 0.15
  dropout1: 0.15
  kernel_size: 3

DATA:
  dataset_name: TriDataset