

GENERAL:
  seed: 2021
  log_path: ./logs
  
TRAINING:
  num_k: 2
  batch_size: 128
  loss: MSE
  optimizer: adam
  learning_rate: 1.0e-4
  num_epochs: 200
  monitor: PearsonCorrCoef
  mode: min
  early_stopping:
    patience: 10
  lr_scheduler:
    patience: 5
    factor: 0.1
  
MODEL:
  model_name: BLEEP
  temperature: 1.0
  image_embedding: 512
  spot_embedding: 50
  projection_dim: 512
  trainable: True
  dropout: 0.1

DATA:
  data_dir: input/hest/bench_data/SKCM
  output_dir: output/hest/bench_data/SKCM
  dataset_name: BleepDataset
  gene_type: 'var'
  num_genes: 50
  num_outputs: 50
  
  train_dataloader:
        batch_size: 128
        num_workers: 4
        pin_memory: False
        shuffle: True

  test_dataloader:
      batch_size: 1
      num_workers: 4
      pin_memory: False
      shuffle: False