

GENERAL:
  seed: 2021
  log_path: ./logs
  
TRAINING:
  num_k: 5
  batch_size: 128
  loss: MSE
  optimizer: adam
  learning_rate: 1.0e-4
  num_epochs: 200
  early_stopping:
    monitor: val_MeanSquaredError
    patience: 20
    mode: min
  lr_scheduler:
    monitor: val_MeanSquaredError
    patience: 5
    factor: 0.1
    mode: min
  
MODEL:
  model_name: TRIPLEX 
  num_outputs: 1000
  emb_dim: 1024
  depth1: 1
  depth2: 5
  depth3: 4
  num_heads1: 8
  num_heads2: 8
  num_heads3: 8
  mlp_ratio1: 4
  mlp_ratio2: 4
  mlp_ratio3: 4
  dropout1: 0.4
  dropout2: 0.3
  dropout3: 0.3
  kernel_size: 3
  learning_rate: 0.0001

DATA:
  data_dir: input/smc/brain
  dataset_name: tri_dataset
  gene_type: 'mean'
  num_outputs: 1000
  
  train_dataloader:
        batch_size: 128 
        num_workers: 4
        pin_memory: True
        shuffle: True

  test_dataloader:
      batch_size: 1
      num_workers: 4
      pin_memory: True
      shuffle: False