

GENERAL:
  seed: 2021
  log_path: ./logs
  
TRAINING:
  num_k: 4
  learning_rate: 1.0e-4
  num_epochs: 200
  monitor: PearsonCorrCoef
  mode: max
  early_stopping:
    patience: 10
  lr_scheduler:
    patience: 5
    factor: 0.1
  
MODEL:
  model_name: TRIPLEX 
  num_outputs: 250
  emb_dim: 1024
  depth1: 2
  depth2: 2
  depth3: 4
  num_heads1: 8
  num_heads2: 16
  num_heads3: 16
  mlp_ratio1: 2
  mlp_ratio2: 2
  mlp_ratio3: 2
  dropout1: 0.15
  dropout1: 0.15
  dropout1: 0.15
  kernel_size: 3
  cpm: True
  smooth: True

DATA:
  data_dir: input/ST/bryan
  output_dir: output/ST/bryan
  dataset_name: TriDataset
  gene_type: 'mean'
  num_genes: 1000
  num_outputs: 250
  
  train_dataloader:
        batch_size: 128
        num_workers: 4
        pin_memory: False
        shuffle: True

  test_dataloader:
      batch_size: 1
      num_workers: 4
      pin_memory: False
      shuffle: False